name: Test and publish release

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Get release version
        id: version
        run: echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Show version
        run: echo "${{ steps.version.outputs.version }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: YC Docker registry login
        run: >-
          cat << EOT | docker login --username json_key --password-stdin cr.yandex
            ${{ secrets.YC_REGISTRY_SECRET }}
          EOT
      - name: Package JAR
        run: mvn test -B package --file pom.xml
      - name: Build image
        run: "docker build -t cr.yandex/crpv1hole0ar4mc982tj/test-app:${{ steps.version.outputs.version }} ."
      - name: Push image
        run: "docker push cr.yandex/crpv1hole0ar4mc982tj/test-app:${{ steps.version.outputs.version }}"
